
development:
  adapter:  mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: game_of_thrones_development
  username: root
  password: mmm_
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

test:
  adapter:  mysql2
  encoding: utf8
  database: game_of_thrones_test
  username: root
  password: mmm_
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

production:
  adapter:  mysql2
  host:     localhost
  encoding: UTF8
  database: game_of_thrones_production
  username: game_of_thrones
  password: mmm_
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
